#ifndef HHCLASSACTIVITY_GLOBAL_H
#define HHCLASSACTIVITY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HHCLASSACTIVITY_LIBRARY)
#  define HHCLASSACTIVITYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define HHCLASSACTIVITYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HHCLASSACTIVITY_GLOBAL_H
