#ifndef HHSCENARIOCONTROLACTIONS_GLOBAL_H
#define HHSCENARIOCONTROLACTIONS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HHSCENARIOCONTROLACTIONS_LIBRARY)
#  define HHSCENARIOCONTROLACTIONSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define HHSCENARIOCONTROLACTIONSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HHSCENARIOCONTROLACTIONS_GLOBAL_H
