#ifndef LIB_FRAMECONTROLLER_GLOBAL_H
#define LIB_FRAMECONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FRAMECONTROLLER_LIBRARY)
#  define FRAMECONTROLLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FRAMECONTROLLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIB_FRAMECONTROLLER_GLOBAL_H
